axis_linear:
  x: 1          #Left Joystick Up/Down
  y: 0          #Left Joystick Left/Right
scale_linear:
  x: 0.4
  y: 0.4
scale_linear_turbo:
  x: 0.8
  y: 0.8

axis_angular:
  yaw: 3        #Right Joystick Left/Right
scale_angular:
  yaw: 0.6
scale_linear_turbo:
  yaw: 1.0

#Enable Button Setting
enable_button: 4
enable_turbo_button: 6
